### ISSUE TITLE
provide text with a function

### ISSUE THREAD

**Issue by tonyhallett** [nkbt/react-copy-to-clipboard#128]
Rather than having to keep in state.

**Comment by nkbt** [comment]
Could you elaborate please? I do not understand what you mean.

**Comment by tomvalorsa** [comment]
I think @tonyhallett is referring to the `text` prop, which currently requires string. It would be useful if this prop accepted a function as well which could be used to generate a string when the copy button is clicked, rather than having to update/maintain a string value in state (as shown in the example). Could be useful if the generation of this string is more complex/expensive.

**Comment by nkbt** [comment]
Why not use copy-to-clipboard lib directly then?

**Comment by tomvalorsa** [comment]
Yeah I ended up just doing that.

Just thought I'd try and provide some clarity on the initial post as I ran into the same issue.

**Comment by nkbt** [comment]
Sure. I just think if you need a function then original lib gives you exactly that and there is no sense using react wrapper for it

**Comment by tonyhallett** [comment]
true could use directly.

I just think that the main purpose of react-copy-to-clipboard is single responsibility ( why else was it created ? )

As such, to me this is better.
`
<Clipboard text={this.getText} options={this.clipboardOptions}>
  <ThingWithOnClick/>
</Clipboard>

than
`
<ThingWithOnClick onClick={()=>copy(this.getText(),this.clipboardOptions)}/>
`

Without the function there are circumstances where react-copy-to-clipboard cannot be used and given that text is only required when the child onClicks it should not be a requirement to provide via state.

**Comment by tomvalorsa** [comment]
@tonyhallett to clarify, I just used `copy-to-clipboard` by itself:

```
const handleCopy = () => {
  // do stuff

  copy(text, options)
}

<button onClick={this.handleCopy} />
```

**Comment by nkbt** [comment]
To me personally
```
<Clipboard text={this.getText} options={this.clipboardOptions}>
  <ThingWithOnClick/>
</Clipboard>
```
cannot be possibly better then
```
const onClick = useCallback(() => copyToClipboard(generateSomeText()))

<button onClick={onClick}>Copy</button>
```

Former adds complexity by introducing its own custom API on top of (1) React and (2) copy-to-clipboard. Latter just uses both directly without having any extra APIs in the middle. Clean and simple.

But this is only my personal opinion of course.

**Comment by tonyhallett** [comment]
@nkbt Then there is no need for react-copy-to-clipboard at all then in your opinion ?!

**Comment by nkbt** [comment]
@tonyhallett we use it a lot as a little thing that lets you set some text and copy it. But just look at the source code - it does not really do much by itself. Up to you if you need it.

**Comment by tonyhallett** [comment]
I have already checked the source, copied it and amended it to accept text as a function.  I only posted as an issue because in my opinion it makes sense for the code to ask me for the text when it is required, whether my response is already present in state or otherwise.

Up to you if you need it.

@tomvalorsa seems to agree.

Also given

> To me personally

```
<Clipboard text={this.getText} options={this.clipboardOptions}>
  <ThingWithOnClick/>
</Clipboard>
```

> cannot be possibly better then

```
const onClick = useCallback(() => copyToClipboard(generateSomeText()))

<button onClick={onClick}>Copy</button>
```
--
Why are you using react-copy-to-clipboard and not taking your own advice ?

`
<button onClick={()=>copy(this.state.text)}>Copy</button>
`

**Comment by nkbt** [comment]
@tonyhallett because I do not need to have any other functions anywhere

```
const url = useRouterUrl();

return (
  <CopyToClipboard text={`${APP_DOMAIN}${url}`}>
    <button type="button" className={css.copyButton}>Copy</button>
  </CopyToClipboard>
);
```

My only point here is that if you are to use a function there - I cannot see much reason using CopyToClipboard component then as you can just use pure functional version of underlying library as is. The code will be the same, but you end up using one less library.

The only reason I could see if we are having all these usecases here and there, somewhere text, somewhere function - then you kind of wan everything to be "normalised" and keep using same library everywhere. That would probably make sense after all.
