### ISSUE TITLE
What's the reason not use ES6 for creating classes?

### ISSUE THREAD

**Issue by cht8687** [nkbt/react-copy-to-clipboard#7]
Hi Nick, this is Robert. I've been to Sydjs too and listened your talk.

I saw you wrote quite a lot React component packages. And you are using ES6, however, what's the reason that you still use 

const App = React.createClass({ }); 

instead of using  ES6:

class App extends React.Component {  }

is there any special reason or benefits for writing those in old method?

cheers

**Comment by nkbt** [comment]
Hi, @cht8687! 
I have 2 reasons for that:
1. The most important reason not to use classes is my personal resistance to classes in JS in general. I genuinely believe adding classes to es6 was not a good idea and is a big step backward from going functional.
2. Class-way is still poorly documented so it is quite hard to share my work with less experienced developers, since they cannot find good working examples and docs.

**Comment by nkbt** [comment]
Also check out this: https://medium.com/javascript-scene/how-to-fix-the-es6-class-keyword-2d42bb3f4caf

**Comment by cht8687** [comment]
oh, thank you for the explanation. Good works. You are working quite hard, this is Saturday morning.

**Comment by nkbt** [comment]
haha, no worries! I'm going to surf in a moment and you won't hear from me for hours =)
